const API_VERSION = process.env.NEXT_PUBLIC_API_VERSION;
const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL;
const APP_BASE_DOMAIN = process.env.NEXT_PUBLIC_APP_BASE_DOMAIN;

const AUTH_USER = "LUXPRO_AUTH_USER";

export { API_VERSION, API_BASE_URL, APP_BASE_DOMAIN, AUTH_USER };
